### ISSUE TITLE
any progress yet?

### ISSUE THREAD

**Issue by jimmieliu** [darshanmakwana412/Imagic#1]
Hi, good to know there is a repo about Imagic. Is there any code or checkpoint you are releasing?

**Comment by darshanmakwana412** [comment]
Hi @jimmieliu , thanks for commenting. Currently we are still in the phase of preprocessing the data for it. We won't be able to release the code or the checkpoints even after the training is complete

**Comment by jimmieliu** [comment]
oh, ok. better knowing, thx
